### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Scxredx** [SanjaySunil/BetterDiscordPanel#106]
every time it says invalid token

**Comment by ducanh2002123** [comment]
Can you please try to follow https://github.com/SanjaySunil/BetterDiscordPanel/issues/99#issuecomment-972967095 and see if it help please?

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.
