### ISSUE TITLE
Pls Update 

### ISSUE THREAD

**Issue by Maxey1950** [SanjaySunil/BetterDiscordPanel#107]
I put in my token and it says  Token is Invalid. Please try again. and i checked regenerte it put in new one pls update this

**Comment by ducanh2002123** [comment]
Can you try the step in this please? https://github.com/SanjaySunil/BetterDiscordPanel/issues/99#issuecomment-972967095

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.
