### ISSUE TITLE
[BUG] token invaild error

### ISSUE THREAD

**Issue by kontmanstein** [SanjaySunil/BetterDiscordPanel#110]
#### How major is the bug from 1 - 10
- Scale: 

#### What type of bug is it?
- Type: 

#### Steps required to reproduce the bug
- Steps:

#### Screenshot (In most cases required)
- Screenshot:

**Comment by cokie1479** [comment]
Scale: 10

Type: token login

Steps: open index.html, put token in the input field

Screenshot:![Screen Shot 2021-11-23 at 7 51 13 PM](https://user-images.githubusercontent.com/70733789/143171940-0b5a8f76-8292-4017-818c-7ae68827b2b6.png)

**Comment by cokie1479** [comment]
![Screen Shot 2021-11-23 at 8 14 18 PM](https://user-images.githubusercontent.com/70733789/143173886-58592272-a327-4ca8-b8bb-f13a8d93e839.png)

**Comment by meatballsong1** [comment]
It looks like you need an Access-Control-Allow-Origin header to access the api.
Look s like an easy fix to me.

**Comment by meatballsong1** [comment]
Adding on to that, I'm still investigating the matter.
Seems like a harder fix.

**Comment by nsde** [comment]
same problem for me

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.

**Comment by cokie1479** [comment]
im sorry i don't understand what to put here


![Screen Shot 2021-11-28 at 9 50 53 AM](https://user-images.githubusercontent.com/70733789/143779770-5b092d44-13e5-43ef-a75e-4238f8b2a631.png)

**Comment by cokie1479** [comment]
oh i got it working but i cant send messages

**Comment by meatballsong1** [comment]
just put the example lmao
