### ISSUE TITLE
Token is Invalid. [BUG]

### ISSUE THREAD

**Issue by Duck-Hunter** [SanjaySunil/BetterDiscordPanel#114]
#### How major is the bug from 1 - 10
- Scale: 9

#### What type of bug is it?
- Type: Can't login

#### Steps required to reproduce the bug
- Steps: Login put the token and it's show "Token is Invalid."

#### Screenshot (In most cases required)
- Screenshot: https://media.discordapp.net/attachments/913893238266531882/914216033479442493/unknown.png?width=1164&height=655

**Comment by Doritogon303** [comment]
same

**Comment by RBXCommunity** [comment]
same for mw

**Comment by RBXCommunity** [comment]
me

**Comment by SanjaySunil** [comment]
Please use this solution. https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md
