### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RBXCommunity** [SanjaySunil/BetterDiscordPanel#115]
#### How major is the bug from 1 - 10
- Scale: 
5/10
#### What type of bug is it?
- Type: 
unable to login with token says invalid but its valid
#### Steps required to reproduce the bug
- Steps:
copy a token and pase it and it says invalid
#### Screenshot (In most cases required)
- Screenshot:
i cant sadly

**Comment by SanjaySunil** [comment]
Please use this solution. https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md
