### ISSUE TITLE
[BUG] Cant send messsage 

### ISSUE THREAD

**Issue by Maxey1950** [SanjaySunil/BetterDiscordPanel#116]
I am in betterdiscordpanel i folllwed you steps but when i invited the but with adminstrator i could not make him tlak it just say send message but does not send Pls fix

**Comment by Maxey1950** [comment]
@everyone

**Comment by Maxey1950** [comment]
@Toshimichi0915 @Marijn2341 @GreepTheSheep @GabiK65 Pls help

**Comment by Toshimichi0915** [comment]
Can you provide error logs in chrome console tab? (make sure to follow [this tutorial](https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md))
Also stop randomly pinging people.

**Comment by Maxey1950** [comment]
Okay my probeln is done but also is there a way to see dms in the bot
?

**Comment by SanjaySunil** [comment]
Viewing DMs has been removed temporarily.

**Comment by Maxey1950** [comment]
When will ut come back

**Comment by SanjaySunil** [comment]
Whenever I have time to work on it.
