### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 13adoo** [SanjaySunil/BetterDiscordPanel#117]
This was passed to me by a friend and the truth before it worked for me no longer and my error is that the token that works takes it as TOKEN INVALID? help
Screen: 
![image](https://user-images.githubusercontent.com/92889906/143782658-338e93cb-0a1b-49ce-a236-4aba04dfc0bc.png)

**Comment by SanjaySunil** [comment]
Please use this solution. https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md
