### ISSUE TITLE
[BUG] Cant send DM to anyone

### ISSUE THREAD

**Issue by Microngamer** [SanjaySunil/BetterDiscordPanel#118]
#### How major is the bug from 1 - 10
- Scale: 5

#### What type of bug is it?
- Type: I cant view DMS page, to talk with people via my bot in DMS

#### Steps required to reproduce the bug
- Steps:

#### Screenshot (In most cases required)
- Screenshot:

**Comment by SanjaySunil** [comment]
DMs is a removed feature on BetterDiscordPanel. I will add this feature back in the future.
