### ISSUE TITLE
[SUGGESTION] Normal account login (IF NOT ALREADY WORKING)

### ISSUE THREAD

**Issue by ytJsuther** [SanjaySunil/BetterDiscordPanel#124]
#### Suggestion Type
- Type: 
  Normal account login 
- Description: 
 Let users login with their normal discord account through their account token
#### How would it help?
Places like school block [discord.com](https://discord.com) but this site is unblocked and self hostable. If we can login with an account token we can access discord at school

I don't know if this works yet as I need to get my token at home, but it'll be a great addition if not working yet!
Just need to save the token on a note on school device, and paste into the app
#### Preview of the change
- Screenshots:
 Don't have any
- Script:
  Don't know

**Comment by SanjaySunil** [comment]
This is against the Discord ToS. BetterDiscordPanel can only be used for discord bots, not user accounts.
