### ISSUE TITLE
[BUG] Invalid Token (ONLY WHEN ACCESSING WEBAPP, ELECTRON WORKS PERFECTLY)

### ISSUE THREAD

**Issue by 13-05** [SanjaySunil/BetterDiscordPanel#140]
#### How major is the bug from 1 - 10
- Scale: 8

#### What type of bug is it?
- Type: Token gets marked as invalid due to CORS.

#### Steps required to reproduce the bug
1) `cd` into the `BetterDiscordPanel` folder.
2) run http-server
3) open the url `http://127.0.0.1:8080/` in your browser of choice (I used firefox)
4) log in; it wont work

#### Screenshots (In most cases required)
- Screenshots:
![image](https://user-images.githubusercontent.com/64506392/146686853-d58d1fa6-0335-4b9a-8e2a-c8a24e534efc.png)
![image](https://user-images.githubusercontent.com/64506392/146686843-eae12ebe-5f44-491b-850e-e9180f6bf424.png)

**Comment by SanjaySunil** [comment]
Please make sure you have followed the instructions [here](https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md).

If your problem has not been resolved, please send a screenshot of the developer console.

**Comment by SanjaySunil** [comment]
You haven't set the custom user agent.

On Firefox:
1. Type in your search bar `about:config`
2. Click on `Search preference name`
3. Type `general.useragent.override`
4. Select the string option and click the add button.
5. Enter any custom user agent string such as `BDP (http://example.com), v0.0.1)`

**Comment by 13-05** [comment]
This worked, thanks!
