### ISSUE TITLE
Bug invalid token even though token is correct 

### ISSUE THREAD

**Issue by Shaxpartan** [SanjaySunil/BetterDiscordPanel#146]

**Comment by ProxyC0ding** [comment]
It happens to me too.

**Comment by SanjaySunil** [comment]
Please provide more information about this problem, including a screenshot of the console.

Please make sure you have followed the instructions [here](https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md) to set a custom user agent.

**Comment by Shaxpartan** [comment]
THAN YOU IT WORKED NOW
