### ISSUE TITLE
[BUG] Token is Invalid. Please try again.

### ISSUE THREAD

**Issue by zhamdaoui73** [SanjaySunil/BetterDiscordPanel#147]
#### How major is the bug from 1 - 10
- Scale: 8

#### What type of bug is it?
- Type: Token is Invalid. Please try again.

#### Steps required to reproduce the bug
- Steps: Login with any token `User/Bot`

#### Screenshot (In most cases required)
- Screenshot:
![image](https://user-images.githubusercontent.com/59831000/147384802-e33f8c78-a87b-48c8-90bb-7367feee5184.png)

**Comment by SanjaySunil** [comment]
Please make sure you have followed the instructions [here](https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md) to set a custom user agent.

If your problem has not been resolved, please send a screenshot of the developer console.

**Comment by zhamdaoui73** [comment]
![image](https://user-images.githubusercontent.com/59831000/147561480-911f83e9-dcca-4d9b-ad07-c559f7bd5f50.png)
Solved :)
Thx
