### ISSUE TITLE
custom user agent doesn't work [BUG]

### ISSUE THREAD

**Issue by DevourerOfGod** [SanjaySunil/BetterDiscordPanel#148]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type:  invalid token

#### Steps required to reproduce the bug
- Steps: login

#### Screenshot (In most cases required)
- Screenshot: https://lol.nothing-to-see-he.re/5k3FxYPnQ

**Comment by SanjaySunil** [comment]
Please use another custom user agent string such as `DiscordBot (https://example.com, v0.0.1)`.
