### ISSUE TITLE
[BUG]when i enter my bots token it just says not correct.

### ISSUE THREAD

**Issue by blowreal** [SanjaySunil/BetterDiscordPanel#159]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: login

#### Steps required to reproduce the bug
- Steps: Enter a token

#### Screenshot (In most cases required)
- Screenshot:
![image](https://user-images.githubusercontent.com/78433751/151712386-f3bf4f3f-b8ea-47ed-a5fe-b60e81726f89.png)

**Comment by blowreal** [comment]
the fix worked

**Comment by blowreal** [comment]
the fix worked

**Comment by MNDL-27** [comment]
> the fix worked

what fix?
