### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by SFCADMIN74** [SanjaySunil/BetterDiscordPanel#216]
#### Suggestion Type
- Type: 
Chat/dms
- Description: 
Allows you to see DMs the bot receives, and allows the bot to send DMS
#### How would it help?
You see this way I can prank people
#### Preview of the change
- Screenshots:
Have none
- Script:
Look I don't know how to code in the language BetterDiscordPanel uses

**Comment by SanjaySunil** [comment]
I have already added this to the [to-do list](https://github.com/SanjaySunil/BetterDiscordPanel/projects/1#card-50413823).
