### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by ilyyerin** [SanjaySunil/BetterDiscordPanel#217]
#### Suggestion Type
- Type: Extra Feature - Manage Server

- Description: Allow the bot to manage the server, IE: add roles, give roles to members, etc. 

#### Preview of the change
- Screenshots:

- Script:

**Comment by SanjaySunil** [comment]
Already added to suggestions. https://github.com/SanjaySunil/BetterDiscordPanel/issues/5
