### ISSUE TITLE
[BUG] My bot got quarantined because of the program opening several DMs at once

### ISSUE THREAD

**Issue by karimawii** [SanjaySunil/BetterDiscordPanel#38]
Hey, I used the panel before, it's really good and has many features, but there's a problem, I used it only once.... and my bot got quarantined, my bot is not a spam, if it was... it shouldn't be verified now, it appears that opening several DM's with all people in all servers makes discord think you're a spam, and that's probably why my bot got quarantined immediatly after using your panel maybe a couple of seconds after closing it, I went to check how many servers the bot reached and got the quarantine message:

![image](https://user-images.githubusercontent.com/69881381/115481977-ee5a2a00-a24d-11eb-9cda-cba84e2cf329.png)
![image](https://user-images.githubusercontent.com/69881381/115482022-0631ae00-a24e-11eb-9114-aa8c7f6bb966.png)

I then reached the support, they removed the quarantine, but they said this:

![image](https://user-images.githubusercontent.com/69881381/115482084-26fa0380-a24e-11eb-97e5-617f31ee47fb.png)

I have only one script running on my bot's token, which is the bot's main code and it doesn't contain any kind of mass-opening DM's functions, so the problem is hundred percent because of the panel, I just want to use the panel again without being afraid of that happening again, but I can't risk getting my bot quarantined again, so please, if you can make dms open only when you click on a user to DM him/her or if there's any problem that caused discord's antispam system to flag my bot please, you need to figure it out.

Thank you

**Comment by karimawii** [comment]
please note that my bot was on a 100 servers at that time, because when I tried it later on another test bot that's only in one server it didn't trigger the antispam system, so it appears that the panel system opened several dms that triggered Discord's antispam system.

**Comment by SanjaySunil** [comment]
Hey, I believe this isn't an issue caused by BetterDiscordPanel because there are no DM functions available. 
What version of the panel did you have?
