### ISSUE TITLE
[SUGGESTION] Embeds

### ISSUE THREAD

**Issue by devilAPI** [SanjaySunil/BetterDiscordPanel#43]
#### Suggestion Type
- Type: Feature

- Description: Make an embed editor to send embeds

#### How would it help?

idk, making embeds?

#### Preview of the change
- Screenshots:
![embededit](https://user-images.githubusercontent.com/52862870/116509906-5c44c800-a8c4-11eb-938e-048c32954964.png)
- Script:

**Comment by SanjaySunil** [comment]
Added to suggestions, thanks!
