### ISSUE TITLE
[BUG] Cant login to bot using token

### ISSUE THREAD

**Issue by Presented** [SanjaySunil/BetterDiscordPanel#47]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: Login

#### Steps required to reproduce the bug
- Steps: I paste the bot token and it does not work, I even tried other code strings to make sure I wasn't pasting the wrong one.

#### Screenshot (In most cases required)
- Screenshot: (its a gif)
![trying to login](https://user-images.githubusercontent.com/31171739/117915504-68148f00-b2b3-11eb-973c-defda45a087d.gif)

PS: It also keeps refreshing when I do nothing

**Comment by devilAPI** [comment]
I never had this Problem, maybe its an error with your webspace?
