### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mishal321** [SanjaySunil/BetterDiscordPanel#48]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: this will not let you in, just bunch of errors

#### Steps required to reproduce the bug
- Steps: login with ur token

#### Screenshot (In most cases required)
- Screenshot:
![image](https://user-images.githubusercontent.com/72044822/118413208-bafb9700-b663-11eb-8b83-f2eb2d948427.png)

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel/issues/94.
