### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fran938** [SanjaySunil/BetterDiscordPanel#58]
#### How major is the bug from 1 - 10
- Scale: 
10
#### What type of bug is it?
- Type: 
i cant use it
#### Steps required to reproduce the bug
- Steps:
in the login screen i cant click in login
#### Screenshot (In most cases required)
- Screenshot:

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel.
