### ISSUE TITLE
I can't login.

### ISSUE THREAD

**Issue by EndyFromMc** [SanjaySunil/BetterDiscordPanel#60]
Hi!

I have a problem with BetterDiscordPanel

I can not sign in.

Can you help me?

I have a token but when I enter it the program restarts and wants a token for me.

So I enter it but the program restarts again.

How can I sign up for a bot?

Thank you in advance.

Goodbye.

**Comment by Daniellop1** [comment]
Have you verified that the bot token is valid?

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel.
