### ISSUE TITLE
[BUG] I can't login in firefox

### ISSUE THREAD

**Issue by Gyur1** [SanjaySunil/BetterDiscordPanel#62]
#### How major is the bug from 1 - 10
- Scale: 10 lol
#### What type of bug is it?
- Type: Login error
#### Video (In most cases required)
- Video: https://imgur.com/h3Ls3A5

(I checked the token its working on chrome)

**Comment by rayjay7225** [comment]
can you set this to on and send a screenshot? i just want to test my theory
![image](https://user-images.githubusercontent.com/79537106/138335123-adf46a3e-1a19-4f4a-9857-821589c6ce53.png)
