### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rayjay7225** [SanjaySunil/BetterDiscordPanel#67]
#### How major is the bug from 1 - 10
- Scale: 1

#### What type of bug is it?
- Type: mild error

#### Steps required to reproduce the bug
- Steps: 
1- move a button on the left
2- move as little as possible to the top of the clickable location until it does that (some buttons don't do that)

#### Video
- Video:

https://user-images.githubusercontent.com/79537106/138202281-a103b6d8-a8c9-4b2d-b905-b21fc8bf7f4f.mp4

**Comment by SanjaySunil** [comment]
I cannot seem to reproduce this, and it doesn't seem like a major problem.
