### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Laccsss** [SanjaySunil/BetterDiscordPanel#75]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: Unable to login

#### Steps required to reproduce the bug
- Steps: Go to the login page and paste token

#### Screenshot (In most cases required)
- Screenshot:
![Screenshot_6](https://user-images.githubusercontent.com/35138280/138734865-6301f7ee-d8e6-41f3-a726-c972e943eb1b.png)

Additional side note: The bot is sharded and has over 100 servers.

**Comment by Laccsss** [comment]
![image](https://user-images.githubusercontent.com/35138280/139540543-feb082b2-9bb4-49d0-9363-78c036d045e6.png)

**Comment by SanjaySunil** [comment]
As the error states, your bot is currently in a lot of servers. You will need to add sharding to it.

**Comment by Laccsss** [comment]
> As the error states, your bot is currently in a lot of servers. You will need to add sharding to it.

Our bot is sharded. 
![image](https://user-images.githubusercontent.com/35138280/143283093-1e511427-11f1-430e-bba8-690889525d89.png)

**Comment by danyalassi** [comment]
How?

Op wo 24 nov. 2021 om 18:04 schreef Laccs ***@***.***>:

**Comment by Laccsss** [comment]
> 

What do you mean how?
