### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luis996** [SanjaySunil/BetterDiscordPanel#84]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: i cant login

#### Steps required to reproduce the bug
- Steps: i just put the token and it dont work

#### Screenshot (In most cases required)
- Screenshot: 
![image](https://user-images.githubusercontent.com/52387429/139486835-56f1e730-c670-457c-9728-25cbf8d7f781.png)

**Comment by BuckyTM** [comment]
Having the same issue, after regenning the token even

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel/issues/94.
