### ISSUE TITLE
How to use the "command" side?

### ISSUE THREAD

**Issue by Codexshield** [SanjaySunil/BetterDiscordPanel#87]
Hello, I would like to know how to use the "order" part? and also how to answer in mp to people who write to us? 
![Capture d’écran 2021-11-03 193007](https://user-images.githubusercontent.com/81874264/140171206-f29cc669-52c7-407e-a373-24df3b063033.png)

**Comment by SanjaySunil** [comment]
The eval function executes any javascript you enter.
For example: `client.guilds.cache.size` returns the number of guilds that the bot is currently in.

**Comment by Codexshield** [comment]
> La fonction eval exécute tout javascript que vous entrez. Par exemple : `client.guilds.cache.size`renvoie le nombre de guildes dans lesquelles se trouve actuellement le bot.

Est-ce que le bot peut effectuer des commande de modération ?

**Comment by Codexshield** [comment]
Et comment peut t'on répondre par messag privé ?

**Comment by SanjaySunil** [comment]
Responding to private messages was a removed feature.
