### ISSUE TITLE
[BUG] Firefox reload in continue

### ISSUE THREAD

**Issue by Mathildeuh** [SanjaySunil/BetterDiscordPanel#89]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: Crash

#### Steps required to reproduce the bug
- Steps: FireFox

#### Screenshot (In most cases required)
- Screenshot: No

**Comment by SanjaySunil** [comment]
Please explain with more detail.

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel.
