### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lez1S** [SanjaySunil/BetterDiscordPanel#93]
well i dont know how to use the template but

when i try to login in my bot i get this error: Invalid Token

earlier it worked good, this error wasnt appearing

who can help me?
![image](https://user-images.githubusercontent.com/81176188/141301570-525b4806-0581-4368-9f53-803a45bc1060.png)

**Comment by Lez1S** [comment]
by the way, it doesnt works even if you download another sample

**Comment by rvp178** [comment]
I got the same issue too

**Comment by Avitii** [comment]
me too

**Comment by CesarPetrescu** [comment]
me 2

**Comment by knabb215** [comment]
Please merge this with #94 
This error seems to be caused by a CORS policy change at Discord.

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel/issues/94.
