### ISSUE TITLE
[BUG]: Requests to Discord has been blocked

### ISSUE THREAD

**Issue by KyleOccidental** [SanjaySunil/BetterDiscordPanel#94]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: it says the token is expired and its not working

#### Steps required to reproduce the bug
- Steps: 

#### Screenshot (In most cases required)
- Screenshot: 
![image](https://user-images.githubusercontent.com/82426268/141317043-ccceae90-cc7a-4cbf-ba36-a8330a5b4b31.png)

**Comment by knabb215** [comment]
This appears to be caused by a CORS policy.
See the attached screencap.

![msedge_gE8jMHf8uB](https://user-images.githubusercontent.com/16668654/141385282-e2b01ce6-ae9c-462f-8ca9-b729547460ba.png)

**Comment by AlzheTV** [comment]
Hello.

I have the exactly SAME error.
![image](https://user-images.githubusercontent.com/68754021/141385672-77a0673e-81df-4985-b566-9a412ad73d0c.png)

Discord blocked webrequests ?
I'm not developper, just using this for reading messages from a web panel for anonymous support solutions.

**Comment by knabb215** [comment]
@AlzheTV It would appear so. It makes me wonder what other changes occurred at Discord overnight. This worked fine yesterday.

**Comment by reed-noc** [comment]
I think Discord patched it

**Comment by knabb215** [comment]
@reed-noc I wonder how that will affect bots with similar functionality to BDP?

**Comment by Codexshield** [comment]
Il est donc réglé le problème ?

**Comment by Code19Master** [comment]
The Same Problem is coming for me, I would request the developer to fix it as soon as possible.

**Comment by sarptekbas** [comment]
Seems like Discord patched it. Discord now only allows requests from their own domains / APIs.

**Comment by Codexshield** [comment]
the problem is resolved ?

**Comment by sarptekbas** [comment]
> 
> 
> the problem is resolved ?

No. Discord changed, not totally, how their servers get requests. From now on Discord will answer to the requests that are only from discord.com and discordapp.com.

**Comment by Codexshield** [comment]
> > le problème est résolu ?
> 
> Non. Discord a changé, pas totalement, la façon dont leurs serveurs reçoivent les requêtes. Désormais, Discord répondra aux demandes qui proviennent uniquement de discord.com et discordapp.com.

So we won’t be able to use the site anymore?

**Comment by sarptekbas** [comment]
> > > le problème est résolu ?
> 
> > 
> 
> > Non. Discord a changé, pas totalement, la façon dont leurs serveurs reçoivent les requêtes. Désormais, Discord répondra aux demandes qui proviennent uniquement de discord.com et discordapp.com.
> 
> 
> 
> So we won’t be able to use the site anymore?

Until there is a way to bypass this CORS policy, no, sadly we can't use BetterDiscordPanel anymore.

**Comment by Codexshield** [comment]
Is there a site like this?
To use our bot on a server?

**Comment by sarptekbas** [comment]
> Is there a site like this?
> 
> To use our bot on a server?
> 
> 

I don't know if you understood what I said, there is no way in hell to use BDP or any other bot client anymore.

**Comment by SanjaySunil** [comment]
I'm afraid that BetterDiscordPanel has been patched. Discord only allows requests from their own domains and APIs. I will keep looking into solutions in

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.
