### ISSUE TITLE
[BUG] Invalid Token

### ISSUE THREAD

**Issue by MafinKingg444** [SanjaySunil/BetterDiscordPanel#95]
#### How major is the bug from 1 - 10
- 10

#### What type of bug is it?
- Type:  Cant Login = every time it say Invalid Token

**Comment by FoxyTails1987** [comment]
Aye that seems about right

**Comment by SanjaySunil** [comment]
See https://github.com/SanjaySunil/BetterDiscordPanel/issues/94.
