### ISSUE TITLE
broke lol[BUG]

### ISSUE THREAD

**Issue by sniperfoxeh** [SanjaySunil/BetterDiscordPanel#97]
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: cant log in

#### Steps required to reproduce the bug
- Steps: try to log in

#### Screenshot (In most cases required)
- Screenshot:

**Comment by DevourerOfGod** [comment]
yup ik.

**Comment by Toshimichi0915** [comment]
Here's how I fixed it:
Change user agent from chrome settings
![image](https://user-images.githubusercontent.com/26406334/141799144-7a72fb88-ef00-4699-936a-2b1b8cbfa537.png)

**Comment by SanjaySunil** [comment]
Thank you for your solution @Toshimichi0915!
