### ISSUE TITLE
Cannot Log In [BUG]

### ISSUE THREAD

**Issue by Gowkrishbeast** [SanjaySunil/BetterDiscordPanel#98]
#### How major is the bug from 1 - 10
- Scale: 9 (Because you basically cannot login, hence making BetterDiscordPanel deprived.)

#### What type of bug is it?
- Type: Logging in to a Discord bot

#### Steps required to reproduce the bug
- Steps: Install the application > Go to "login" file > Enter your Discord bot token & it'll reply with "invalid token"

#### Screenshot (In most cases required)
- Screenshot: I have also connected the exact token I got from Discord, but still
![image](https://user-images.githubusercontent.com/94351359/141742329-ec77ae22-13eb-4aae-94c3-8a9d8f5e107e.png)
 doesn't work

**Comment by Gowkrishbeast** [comment]
If people can help! Thanks

**Comment by DevourerOfGod** [comment]
i want it to so bad. But its broken

**Comment by Toshimichi0915** [comment]
Here's how I fixed it:
Change user agent from chrome settings
![image](https://user-images.githubusercontent.com/26406334/141799144-7a72fb88-ef00-4699-936a-2b1b8cbfa537.png)

**Comment by Codexshield** [comment]
> Voici comment je l'ai corrigé : modifiez l'agent utilisateur à partir des paramètres de chrome ![image](https://user-images.githubusercontent.com/26406334/141799144-7a72fb88-ef00-4699-936a-2b1b8cbfa537.png)

Impossible, not work

**Comment by ducanh2002123** [comment]
> Here's how I fixed it: Change user agent from chrome settings ![image](https://user-images.githubusercontent.com/26406334/141799144-7a72fb88-ef00-4699-936a-2b1b8cbfa537.png)

this fixed my issue too, I had to change it via other mean, but changing the user agent to something more personalized helped!
thanks a lot!

**Comment by Codexshield** [comment]
Make a video to explain please, or add me on discord please to help me : CodexShield#1902

**Comment by ducanh2002123** [comment]
> Make a video to explain please, or add me on discord please to help me : CodexShield#1902

Ah sure, give me a bit, I’ll make a video detailing how to fix it (or you can check this comment by me for the cmd version)
https://github.com/SanjaySunil/BetterDiscordPanel/issues/99#issuecomment-972967095

**Comment by Codexshield** [comment]
> > Faites une vidéo pour expliquer s'il vous plait, ou ajoutez moi sur discord s'il vous plait pour m'aider : CodexShield#1902
> 
> Ah bien sûr, donnez-moi un peu, je vais faire une vidéo détaillant comment y remédier (ou vous pouvez vérifier ce commentaire par moi pour la version cmd) [#99 (commentaire)](https://github.com/SanjaySunil/BetterDiscordPanel/issues/99#issuecomment-972967095)

Could you add me as a friend please ? CodexShield#1902

**Comment by ducanh2002123** [comment]
Well, I just sent a friend request

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.
