### ISSUE TITLE
Saying Token Error Not Logging in [BUG]

### ISSUE THREAD

**Issue by Kabin1234** [SanjaySunil/BetterDiscordPanel#99]
#### How major is the bug from 1 - 10
- Scale:  10

#### What type of bug is it?
- Type:  Logging Error

#### Steps required to reproduce the bug
- Steps: Just Try To Login With The Bot Token

#### Screenshot (In most cases required)
- Screenshot:

**Comment by PROMEDO** [comment]
same problem with you

**Comment by Kabin1234** [comment]
yess

**Comment by Scoooolz** [comment]
> same problem with you
Same

**Comment by Kabin1234** [comment]
yess

**Comment by ducanh2002123** [comment]
How I fixed it:
changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be

win.webContents.userAgent = "some random user agent here"
  win.on('ready-to-show', () => {
    win.maximize();
    win.show();
  });
  hope it helps ya guys

**Comment by Kabin1234** [comment]
It works!  But sunil sir should immediately fix it .

**Comment by cuti1234kl** [comment]
> How I fixed it: changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be
> 
> win.webContents.userAgent = "some random user agent here" win.on('ready-to-show', () => { win.maximize(); win.show(); });
> 
> hope it helps ya guys

làm sao vậy ông, tui bị lỗi ;_;

**Comment by miatoszs** [comment]
> 

Hi wha is random user agent?

**Comment by Code19Master** [comment]
> How I fixed it: changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be
> 
> win.webContents.userAgent = "some random user agent here" win.on('ready-to-show', () => { win.maximize(); win.show(); });
> 
> hope it helps ya guys

can you pls pull request

**Comment by ducanh2002123** [comment]
> > How I fixed it: changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be
> > win.webContents.userAgent = "some random user agent here" win.on('ready-to-show', () => { win.maximize(); win.show(); });
> > hope it helps ya guys
> 
> can you pls pull request

Um, well, I personally think if someone can code an actual good workaround, like an UI or something to randomize the user agent it would be better, because i think pretty much all hard coded value would get blocked by discord, so a value that’s not hard coded in would be better, and I do not know how to make a UI like that :(

**Comment by ducanh2002123** [comment]
> Hi wha is random user agent?

Just type in something random, like IAMABOT/v2.4 or something, and it’ll work

**Comment by ducanh2002123** [comment]
> > How I fixed it: changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be
> > win.webContents.userAgent = "some random user agent here" win.on('ready-to-show', () => { win.maximize(); win.show(); });
> > hope it helps ya guys
> 
> làm sao vậy ông, tui bị lỗi ;_;

Lỗi gì vậy? Mình edit 1 tí cái file là được luôn mà

**Comment by PROMEDO** [comment]
> 

Your explanation is not understandable, explain more with pictures and file name

**Comment by Microngamer** [comment]
> How I fixed it: changing the user-agent header, for the application version (the cmd file version), I added this to the index.js file (only the win.WebContents line is new, the other 2 lines are to show where it's supposed to be
> 
> win.webContents.userAgent = "some random user agent here" win.on('ready-to-show', () => { win.maximize(); win.show(); });
> 
> hope it helps ya guys

Ayy mate ty, could you lmk how to fix it for the index.html ?

**Comment by cokie1479** [comment]
i am having the same problem but i am on mac-os Catalina and am using the index.html

**Comment by nsde** [comment]
same problem here

**Comment by SanjaySunil** [comment]
Please see https://github.com/SanjaySunil/BetterDiscordPanel/blob/master/docs/prerequisites/prerequisites.md.
